version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: remoteshell
      POSTGRES_PASSWORD: remoteshell
      POSTGRES_DB: remoteshell
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: 